# configs/garak_rest_config.yaml  

rest:
  RestGenerator:
    method: post
    headers:
      Content-Type: application/json
    req_template_json_object:
      prompt: "$INPUT"
    response_json: true
    response_json_field: response



