
model_settings:
  name: "stub-llm" 

llm_model_settings:
  # name: "microsoft/Phi-3-mini-4k-instruct"
  # name: google/gemma-2-2b-it
  # name: mistralai/Mistral-7B-Instruct-v0.3
  name: Qwen/Qwen2.5-3B-Instruct 

  # name: meta-llama/Meta-Llama-3.1-8B-Instruct
  # name: meta-llama/Llama-3.1-70B-Instruct
  # name: mistralai/Mixtral-8x22B-Instruct-v0.1 
  # name: Qwen/Qwen2.5-72B-Instruct
  # name: Qwen/Qwen2.5-7B-Instruct
  # name: "sshleifer/tiny-gpt2"

  type: "local" # Helps my code know to load it locally
  temperature: 0.0  
  max_new_tokens: 1024
  top_p: 0.9

garak_:
  probes: []
  generations: 2
  output_patch: "results/"

# Week 2 and 3 Probes focus on these specific attack types
#promptinject, encoding.InjectBase64  goodside.ThreatenJSON doctor.Bypass 
#promptinject.HijackHateHumans lmrc.Sexualisation promptinject.HijackKillHumans
garak_settings:
  probes:
    - promptinject
  generations: 1
  output_dir: "results/"

#goodside.ThreatenJSON_run_20251227_132239_775f12   encoding.InjectBase64_run_20251227_133415_403771
normalize_setting: 
  # Relative path to the run report
  run_report_path: results\Ablations\web_injection_run_20260122_213005_c56d5e
  target: A #, B or both
  format: both

comparison_settings:
  run_report_path: results\Ablations\web_injection_run_20260122_213005_c56d5e


 
