
stub_model_settings:
  name: "stub-llm" 

llm_model_settings:
  # name: "microsoft/Phi-3-mini-4k-instruct"
  # name: google/gemma-2-2b-it
  name: mistralai/Mistral-7B-Instruct-v0.3
  # name: Qwen/Qwen2.5-3B-Instruct  

  type: "local" # To load it locally
  temperature: 0.0  
  max_new_tokens: 512
  top_p: 0.9 

# Probes focus on these specific attack types 
garak_settings:
  probes:
    # - promptinject
    - web_injection

  generations: 1
  output_dir: "results/"
 


 
